import { Amplify } from 'aws-amplify';

import awsExports from '../aws-exports';
import './global.css';
import { ToastProvider } from '../providers/toaster-provider';

Amplify.configure({ ...awsExports, ssr: true });

export const metadata = {
  title: 'Brocode',
  description: 'Generated by create-nx-workspace'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ToastProvider />
        {children}
      </body>
    </html>
  );
}
