/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_appsync_graphqlEndpoint": "https://p6ditsxslbgstpjwibbxwozmym.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-x42arqkd4rbkxer67ys5i4su5m",
    "aws_cognito_identity_pool_id": "eu-north-1:6ea09f5d-4f0a-46e0-8deb-cf9e5416d010",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_WStUh7ZTs",
    "aws_user_pools_web_client_id": "4vmtj77vde004udrr27kfu64aa",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amplify-lms-storage-ab38f492102630-staging",
    "aws_user_files_s3_bucket_region": "eu-north-1"
};


export default awsmobile;
