import './global.css';

export const metadata = {
  title: 'Welcome to apps/yupop',
  description: 'Generated by create-nx-workspace'
};

export default function RootLayout({
  children
}: {
  readonly children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
